[project]
name = "ohmycash"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "matplotlib>=3.10.1",
    "requests>=2.32.3",
    "yadisk>=3.3.0",
]

[tool.ruff]
line-length = 128

[tool.ruff.format]
quote-style = "single"
